Repository Nexters/funch-server, pull requests merged in 2024-02, with the labels that each got.

#31 feat: subway db 데이터 연동 및 mock 데이터 제거
  api/src/main/kotlin/kr/co/funch/api/domain/matching/model/SubwayInfo.kt
  api/src/main/kotlin/kr/co/funch/api/domain/member/SubwayStationService.kt
  api/src/main/kotlin/kr/co/funch/api/domain/member/model/SubwayStation.kt
  api/src/main/kotlin/kr/co/funch/api/interfaces/dto/MemberDto.kt
  api/src/main/kotlin/kr/co/funch/api/interfaces/dto/SubwayStationDto.kt
Labels: ✨ feature

#38 chore:운영 MongoDB 계정 만들기
  .github/workflows/actions-merge.yml
  api/build.gradle.kts
Labels: ⚙️ infra

#48 chore: 매칭 시 memberCode 대소문자 구별하지 않도록 수정
  api/src/main/kotlin/kr/co/funch/api/domain/member/MemberRepository.kt
Labels: 🧚‍♀️ minor

#50 fix: 멤버 매칭 기록 버그 수정
  api/src/main/kotlin/kr/co/funch/api/domain/matching/MatchingRecordService.kt
Labels: 🐞 bug
